---
title: "Sesion 03 - Enfoque de Riesgo Agregado"
author:
-  Juan Carlos Martínez-Ovando
date: "Otoño 2019"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 3
    number_sections: yes
    self_contained: yes
    theme: cerulean # cosmo
    highlight: textmate
fig_align: "center"
fig_width: 18

header-includes:
    - \usepackage[most]{tcolorbox}
    - \usepackage{mathtools}
    - \definecolor{light-yellow}{rgb}{1, 0.95, 0.7}
    - \newtcolorbox{myquote}{colback=light-yellow,grow to right by=-10mm,grow to left by=-10mm, boxrule=0pt,boxsep=0pt,breakable}
    - \newcommand{\todo}[1]{\begin{myquote} \textbf{TODO:} \emph{#1} \end{myquote}}

---

\newcommand{\WiD}{\operatorname{\text{Wi}}}
\newcommand{\WeD}{\operatorname{\text{We}}}
\newcommand{\WeNormD}{\operatorname{\text{We-N}}}
\newcommand{\ExpD}{\operatorname{\text{Exp}}}
\newcommand{\BeD}{\operatorname{\text{Be}}}
\newcommand{\GeoD}{\operatorname{\text{Geo}}}
\newcommand{\StD}{\operatorname{\text{St}}}
\newcommand{\NormD}{\operatorname{\text{N}}}
\newcommand{\GaD}{\operatorname{\text{Ga}}}
\newcommand{\UniD}{\operatorname{\text{U}}}
\newcommand{\DirD}{\operatorname{\text{Dir}}}
\newcommand{\IG}{\operatorname{\text{InG}}}
\newcommand{\IncGa}{\operatorname{\text{IGa}}}
\newcommand{\IGa}{\operatorname{\text{InGa}}}
\newcommand{\PoD}{\operatorname{\text{Po}}}
\newcommand{\BS}{\operatorname{\text{BS}}}
\newcommand{\DP}{\operatorname{\text{DP}}}
\newcommand{\BinD}{\operatorname{\text{Bin}}}
\newcommand{\BinNegD}{\operatorname{\text{BinNeg}}}
\newcommand{\dd}{\mathrm{d}}
\newcommand{\Indic}{\mathbb{I}}
\newcommand{\Borel}{\operatorname{\mathscr{B}}}
\newcommand{\Filtration}{\operatorname{\mathscr{F}}}
\newcommand{\Expec}{\operatorname{\mathbb{E}}}
\newcommand{\Var}{\operatorname{\text{var}}}


# Objetivos


# Agregacion de riesgos

## Notacion

Son modelos estacasticos que miden la incertidumbre asociada con un portafolio de seguros.
	  	
Para esto, se distinguen las siguientes caracteristicas:

* $J$ es la suscripcion de un portafolio de seguros en un periodo de tiempo dado

* $Y_j$ es la variable aleatoria que mide el monto de siniestro de una poliza ($j=1,\ldots,J$)

* $X_j$ es el monto de reclamo del siniestro en la poliza $j$

* $D_j$ es el monto del siniestro a cargo del asegurado

* $Z_j$ es el monto del siniestro a cargo de la reaseguradora


## Agregacion

As\'i, para cada p\'oliza $j=1,\ldots,J$,
\begin{equation}
  Y_j = D_j + X_j + Z_j.
\end{equation}
		
Mientras que,

* $\sum_{j=1}^{J} Y_j$ es la severidad acumulada de siniestros

* $\sum_{j=1}^{J} X_j$ es la severidad acumulada de siniestros a cargo de la aseguradora

## Racionalidad

No todas las p\'olizas experimentaron un siniestro (principio del seguro). As\'i,

a.  En caso de siniestro, $Y_j > 0$

b. En caso de no siniestro, $Y_j = 0$.

De esta forma,

\begin{eqnarray}
	\sum_{j=1}^{J} Y_j
	& = & 
	\sum_{j|Y_j=0} Y_j
	+
	\sum_{j|Y_j>0} Y_j
	\nonumber \\
	& = & 
	\sum_{j} Y_j \Indic(Y_j=0)
	+
	\sum_{j} Y_j \Indic(Y_j>0)
	\nonumber \\
	& = & 
  \sum_{j}^{N} Y_j \Indic(Y_j>0),
\end{eqnarray}
donde,

* $N$ es el n\'umero de siniestros en el periodo dado (a.k.a. frecuencia de siniestros).

## Consideraciones

* Intr\'insecamente, $N$ (antes de observarse) es incierto y aleatorio

* La magnitud individual del siniestro, $Y_j \Indic(Y_j>0)$ (antes de observarse) es incierta y aleatoria, as\'i como la ocurrencia de siniestro, $\Indic(Y_j>0)$.

Para, 
\begin{eqnarray}
S 	& = & 
\sum_{j}^{N} Y_j \Indic(Y_j>0),
\end{eqnarray}
las fuentes de aleatoriedad son:

* $N$ - frecuencia de siniestros

* $S_j$ - severidad individual de siniestros

# Enfoque de riesgo individual

El monto agregado de siniestro, $S$, se define por

* El numero de sumandos (suscripcion total), $J$, considerado como fijo en riesgo operacional (mas no en riesgo de mercado),

* Severidad individual, $Y_j \in \{0\}\cup (0,\infty)$, desconocida y aleatorio, para todo $j=1,\ldots,J$.

## Enfoque de riesgo colectivo

El monto agregado de siniestro, $S$, se define por

* N\'umero de sumandos (frecuencia aleatoria), $N$, desconocido

* Severidad individual, $Y_j \in (0,\infty)$, considerada como desconocida y aleatoria, para todo $j=1,\ldots,J$.

