---
title: "Sesion 06 - Agregacion de Riesgos (Calculo)"
author:
-  Juan Carlos Martínez-Ovando
date: "Otoño 2019"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 3
    number_sections: yes
    self_contained: yes
    theme: cerulean # cosmo
    highlight: textmate
fig_align: "center"
fig_width: 18

header-includes:
    - \usepackage[most]{tcolorbox}
    - \usepackage{mathtools}
    - \definecolor{light-yellow}{rgb}{1, 0.95, 0.7}
    - \newtcolorbox{myquote}{colback=light-yellow,grow to right by=-10mm,grow to left by=-10mm, boxrule=0pt,boxsep=0pt,breakable}
    - \newcommand{\todo}[1]{\begin{myquote} \textbf{TODO:} \emph{#1} \end{myquote}}

---

\newcommand{\WiD}{\operatorname{\text{Wi}}}
\newcommand{\WeD}{\operatorname{\text{We}}}
\newcommand{\WeNormD}{\operatorname{\text{We-N}}}
\newcommand{\ExpD}{\operatorname{\text{Exp}}}
\newcommand{\BeD}{\operatorname{\text{Be}}}
\newcommand{\GeoD}{\operatorname{\text{Geo}}}
\newcommand{\StD}{\operatorname{\text{St}}}
\newcommand{\NormD}{\operatorname{\text{N}}}
\newcommand{\GaD}{\operatorname{\text{Ga}}}
\newcommand{\UniD}{\operatorname{\text{U}}}
\newcommand{\DirD}{\operatorname{\text{Dir}}}
\newcommand{\IG}{\operatorname{\text{InG}}}
\newcommand{\IncGa}{\operatorname{\text{IGa}}}
\newcommand{\IGa}{\operatorname{\text{InGa}}}
\newcommand{\PoD}{\operatorname{\text{Po}}}
\newcommand{\BS}{\operatorname{\text{BS}}}
\newcommand{\DP}{\operatorname{\text{DP}}}
\newcommand{\BinD}{\operatorname{\text{Bin}}}
\newcommand{\BinNegD}{\operatorname{\text{BinNeg}}}
\newcommand{\dd}{\mathrm{d}}
\newcommand{\Indic}{\mathbb{I}}
\newcommand{\Borel}{\operatorname{\mathscr{B}}}
\newcommand{\Filtration}{\operatorname{\mathscr{F}}}
\newcommand{\Expec}{\operatorname{\mathbb{E}}}
\newcommand{\Var}{\operatorname{\text{var}}}


---

# Objetivos

* Estudiar el proceso de agregacion de riesgos, bajo el enfoque de `riesgo individual` particularmente.

---

# Convoluciones y distribuciones compuestas

## Definicion

La *composicion de distribuciones* surge como distribucion de *sumas de variables aleatorias*.

Sean $N_{1},\ldots,N_M$ variables aleatorias no negativas con soporte en los entreros, i.e. $\mathcal{N}=\{0,1,\ldots\}$. Definimos la suma de estas variables como
$$
S=\sum_{m=1}^{M}N_m.
$$

### Casos

* Si $M$ es en si mismo un entero no negativo aleatorio, y $M$ es independiente estocasticamente de $N_1,\ldots,N_M$; se dice que la distriucion de $S$ es una **distribucion compuesta.**

> Este es el caso del `enfoque de riesgo colectivo`.

* Si $M$ es una constante, i.e. la distribucion de $M$ es degenerada en un numero particular, $m$, entonces la distribucion de $S$ es una **convolucion.**

> Este es el caso del `enfoque de riesgo individual`.

### Componentes

a. *Distribucion primaria:* $M\sim F_M(m)$

b. *Distribucion secundaria:* $N_1,\ldots,N_M\sim^{iid} F_N(n)$

## Caso sencillo

Pensemos que $F_M(m)$ es una distribucion degenerada en $m^*>1$. En particular, pensemos que $m^*=2$. En este caso $S$ es la suma de *dos* componentes aleatorios,
$$
S=N_1+N_2.
$$
La distribucion de $S$ la podemos encontrar como la identificacion de las masas de probabilidades
\begin{eqnarray}
p_S(s) & = & \mathbb{P}(N_1+N_2=s)=\mathbb{P}(N_1=s-N_2)\nonumber\\
&=&\sum_{n=0}^{s}\mathbb{P}(N_1=s-n,N_2=n).\nonumber
\end{eqnarray}

---

# Enfoque de riesgo individual

Recordemos, en el modelo de riesgo individual, suponemos que el reclamo de la poliza $j$ es denotado por $X_j$, la cual tiene soporte en 
$$
\mathcal{X}=\{0\} \cup (0,\infty),
$$
para $j=1,\ldots,J_t$, para un momento del tiempo $t$, con $t\geq 1$.

La variable $J_t$ en este caso es **conocida** y **fija** en cada tiempo $t$. Tipicamente representa el total de suscripcion del portafolio de seguros en el periodo de tiempo correspondiente.

---

**Supuesto**

Tradicionalmente se supone en cada periodo de tiempo $t$ los reclamos $X_{tj}$s son _independientes_ y _homogeneos en distribucion_ (i.i.d.), con distribucion marginal data por la distribucion tipo mezcla, 
$$
F_X(x)=\theta\delta_{\{0\}}(x)+(1-\theta)F^{c}_X(x),
$$  
donde $$\theta = \mathbb{P}(\text{no siniestro})$$ y $$F^{c}_X(x)=\mathbb{P}\left(X\leq x|\text{siniestro}\right)$$ representa la `parte continua` de la distribucion, con soporte en $(0,\infty)$.

---

# Monto agregado

Asi, para el periodo de tiempo $t$, el monto agregado de reclamos del portafolio de tamano $J_t$ se define como
$$
S_t = \sum_{j=1}^{J_t} X_{tj}.
$$
Siendo que $J_t$ se considera como un parametro fijo en el modelo, tenemos que 
\begin{eqnarray}
\mathbb{E}(S_t) 
  & = & J_t\mathbb{E}(X) 
  \nonumber \\
var(S_t) 
  & = & J_t var(X),
  \nonumber 
\end{eqnarray}

Denotando los primeros dos momentos de los montos individuales de siniestros como
$$\mu_X = \mathbb{E}\left(X|\text{siniestro}\right)$$ y $$\sigma_X^{2}=var\left(X|\text{siniestro}\right),$$ se obtiene una simplificacion de las ecuaciones enteriores. 

---

Siendo las severidades individuales $X_{tj}$ variables aleatorias del tipo mixta, se tiene que 
\begin{eqnarray}
\mathbb{E}(S_t) 
  & = & J_t(1-\theta)\mu_{X} 
  \nonumber \\
var(S_t) 
  & = & J_t \left(\mu^{2}_X\theta(1-\theta) + (1-\theta)\sigma_{X}^{2}\right). 
  \nonumber 
\end{eqnarray}


Aunque el calculo del primer y segundo momentos de $S_t$ es simple, **necesitamos** cuantificar la incertidumbre completa de $S_t$ a traves de su distribucion exacta,
$$
F_{S_t}(s) = \mathbb{P}\left(\sum_{j=1}^{J_t}X_{tj} \leq s\right),
$$
inducida por $F_X(x)$.

---

# Procedimientos

Hemos visto que esta puede calcularse a traves del siguientes metodos:

A. Convolucion directa

B. Metodo de momentos

C. Simulacion estocastica

D. Aproximacion analitica

E. Recursion


---

## A) Convoluciones

Supongamos que $(X_{tj})_{j=1}^{J_t}$ son variables aleatorias independientes e identicamente distribuidas, con funcion de distribucion $F_X(x)$ y soporte en $\mathcal{X}=(0,\infty)$.

**Caso** $N=2$

Consideremos el caso donde definimos 
$$
S_t=X_{t1}+X_{t2}.
$$

De manera general, para soportes de $\mathcal{X}$en $\Re$, se tiene que,
\begin{eqnarray}
 \mathbb{P}(S_t\leq s) 
   & = &
   \mathbb{P}(X_{t1}+X_{t2}\leq s)
   \nonumber \\
   & = &
   \int_{\mathcal{X}} \mathbb{P}(X_{t1}+X_{t2}\leq s|X_{t2}=x)\mathbb{P}(X_{t2} \in dx)
   \nonumber \\
   & = &
   \int_{\mathcal{X}} F_{X}(s-x)F_X(d x)
   \nonumber \\
   & = &   
   \int_{\mathcal{X}} F_{X}(s-x)f_X(x) dx
   \nonumber \\
   & = &   
   F_X*F_X(s)
   \nonumber \\
   & = &   
   F^{*(2)}_X(s).
   \label{eq_convolution}
\end{eqnarray}

---

Ahora bien, si $X$ tiene soporte en $(0,\infty)$, entonces $F_X(x)$ est\'a determinada por la funci\'on indicadora $\mathbb{I}_{(0,\infty)}(x)$, mientras que $F_X(s-x)$ estar\'a determinada por $\mathbb{I}_{(0,\infty)}(s-x)$, en cuyo caso la integral (\ref{eq_convolution}) se convierte en,
\begin{eqnarray}
\mathbb{P}(S_t\leq s) 
& = &
\mathbb{P}(X_{t1}+X_{t2}\leq s)
\nonumber \\
& = &   
\int_{0}^{s} F_{X}(s-x)f_X(x) dx
\nonumber \\
& = &   
F_X*F_X(s)
\nonumber \\
& = &   
F^{*(2)}_X(s).
\label{eq_convolution_positive}
\end{eqnarray}

---

Siguiendo lo anterior se tiene que en el *ejemplo* donde $X_{t1}$ y $X_{t2}$ son variables aleatorias i.i.d. con distribucion marginal $\text{Exp}(x|\theta)$, con $\theta>0$, se sigue
\begin{eqnarray}
\mathbb{P}(S_t\leq s) 
& = &
\mathbb{P}(X_{t1}+X_{t2}\leq s)
\nonumber \\
& = &   
F^{*(2)}_X(s)
\nonumber \\
& = &
\text{Ga}(s|2,\theta).
\label{eq_convolution_exponential}
\end{eqnarray}

---

**Caso** $N$ **general**

En el caso donde 
$$
S_t=\sum_{i=1}^{J_t}X_{ti},
$$
se sigue (por induccion), bajo los supuestos mencionados antes, que 
\begin{eqnarray}
\mathbb{P}(S_t\leq s) 
& = &
F_X^{*(J_t)}(s|\theta).
\label{eq_convolution_general}
\end{eqnarray}

**NOTA 1:** Solo en casos especificos de $F_X(\cdot)$ pertenecientes a distribuciones en la familia exponencial se pueden obtener expresiones analíticas cerradas para las convoluciones.

**NOTA 2:** En el caso general donde $F_X(\cdot)$ tenga uno o más átomos, la expresión analítica de la convolución es bastante compleja y, en muchos casos, imposible de obtener; aun cuando la parte absolutamente continua de $F_X$ pertenezca a la familia exponencial.

De esta forma, se puede descansar en otros métodos descritos a continuación.

## B) Método de momentos

El método de momentos se basa en la identificación de $F_{S_t}(s)$ a través de su correspondiente función generadora de momentos, $M_{S_t}(w)$ definida como $$M_{S_t}(w)=\mathbb{E}_{F_{S_t}}\left(\exp\{wS_t\}\right).$$
La identificación es única pues la relación entre ambas funciones es $1:1$.

Bajo el supuesto de *independencia y homogeneidad en distribución* se sigue que $$M_{S_t}(w)=\left[M_{X}(w)\right]^{J_t},$$
donde $M_{X}(w)$ es la función generadora de momentos genérica para las $X_{tj}$s.

---

**Ejercicio:** ?`Cómo sería la expresión de $M_{X}(w)$ bajo el supuesto de intercambiabilidad en las $X_{tj}$s?  

De esta forma, **identificando** la forma estructural de $M_{X}(w)$ puede identificarle la forma funcional asociada con $F_{S_t}(s)$. 


---

**Supuestos**

El procedimiento descansa en el supuesto que $M_{X}(w)$ existe y que ésta elevada a una cierta potencia tiene una forma analítica cerrada y conocida.

**Nota:** 

El resultado se generaliza al uso de la *función característica*, $\phi_{X}(w)$, y la *función generadora de probabilidades*, $\rho_{X}(w)$.

---

El reto analitico fundamental de este procedimiento reside en que $F_{X}(x)$ tiene típicamente al menos un punto de discontinuidad en $\{0\}$ (no reclamo por no siniestro), i.e.
$$
F_{X}(x)=\theta \mathbb{I}_{\{0\}}(x) + (1-\theta)F_{X}^{c}(x),
$$
donde $F_{X}^{c}(x)$ corresponde a la parte (absolutamente) continua de $F_{X}(\cdot)$. En este caso, la función generadora de momentos asociada puede verse como la comosición de:

a. Distribución continua para el reclamo, sujeto a un siniestro, i.e.
$$M_{X}^{c}(w)=\mathbb{E}_{F_{X}^{c}}\left(\exp\{w X\}\right),$$
b. Distriución Bernoulli asociada con el eveneto de tener siniestro o no, i.e.
$$M_{\text{Siniestro}}(w)=\theta + (1-\theta)\exp\{w\}.$$

---

Así, la expresión general para $M_{X}(w)$ es la siguiente,
$$
M_{X}(w)=\theta + (1-\theta)\exp\{M_{X}^{c}(w)\}.
$$
Esta expresión tendrá una forma anlítica anipulable en función de que $M_{X}^{c}(w)$ sea simple y compatible con $\exp(\cdot)$.

Empleando la expresión anterior, se sigue (bajo el supuesto de independencia y homogeneidad distribucional en las $X_{tj}$), la función generadora de momentos para $F_{S_t}(s)$ está asociada con $$M_{S_t}(w)=\left[\theta_t + (1-\theta_t)\exp\{M_{X_t}^{c}(w)\}\right]^{J_t}.$$

---

Al rededor de esta expresión debemos anotar dos cosas:

1. La distribución para la ocurrencia de siniestros para un tiempo $t$ dado presupone homogeneidad entre las $\{X_{tj}\}_{j=1}^{J_t}$. Sin embargo, podría hacerce alusión a homogeneidad distribucional a través de $t$.

2. El comentario anterior aplica análogamente a $F_{X_t}^{c}(x)$.

Como podrán anticipar, sólo pocos casos particulares será posible identificar $F_{S_t}(s)$ a través de $M_{S_{t}}(w)$. 

---

## C) Método basado en simulación estocástica

Un método alternativo de calculo/aproximación de $F_{S_t}(s)$ consiste en generar muestras (pseudo) aleatorias de $\{X_{tj}\}_{j=1}^{J_t}$, agregándolas en cada caso descansando en el método de Monte Carlo. Así, el algoritmo se resume en los siguientes pasos:

a. Fijar $K$ número de simulaciones deseadas de $F_{S_t}(s)$ (entre mayor sera $K$ la aproximación será más precisa, pero menos eficiente computacionalente).

b. Para $k=1, \ldots, K$ generar $J_t$ variables pseudo aleatorias de $F_{X_t}(x)$, denottadas por $$\left\{x^{(k)}_{tj}\right\}_{j=1}^{J_t}$$.

c. Para cada $k$, generar la muestra de $F_{S_t}(s)$ correspondiente mediante la agregación de las $x_{tj}^{(k)}$s correspondientes, i.e. $$s_{t}^{(k)}=\sum_{j=1}^{J_t}x^{(k)}_{tj}.$$

d. la colección de datos simulados $\{s_{t}^{(k)}\}_{k=1}^{K}$ corresponde a una muestra aleatoria de $F_{S_t}(s)$.

Usando los recursos computacionales actuales, el método de simulación estocástica resulta ser bastante versátil y útil en la práctica.


## D) Aproximacion analitica

La aproximacion analitica para $F_{S-t}(s)$ descansa en el Teorema Central de Limite (TCL), argumentando que la composicion del portafolio, $J_t$, es relativamente `grande`.

Dado que en teoria se conoce la media y varianza de $S_t$, `suponiendo` que $\mathbb{E}(X)$ y $var(X)$ son `fijos` y `conocidos`, se sigue
\begin{eqnarray}
F_{S_t}(s)
 & = &
 \mathbb{P}\left(S_t \leq s\right)
 \nonumber \\
 & = &
 \mathbb{P}\left(\frac{S_t-\mathbb{E}(S)}{sd(S_t)}\leq \frac{s-\mathbb{E}(S_t)}{sd(S_t)}\right)
 \nonumber \\
 & \approx &
 \mathbb{P}\left( Z \leq \frac{s-\mathbb{E}(S_t)}{sd(S_t)}\right)
 \nonumber \\
 & \approx &
 N\left( S_t | \mathbb{E}(S_t), var(S_t)\right),
 \nonumber
\end{eqnarray}
donde $sd(S) = var(S)^{1/2}$ y $Z \sim N(z|0,1)$. 

---

**Comentarios** 

* El resultado asintotico anterior es valido solo en el caso que $var(X)<\infty,$ (o equivalentemente, sujeto a $\mathbb{E}\left(X^{2}\right)$ sea finito). 

* Esta condicion se cumple solo en el caso en el que las severidades individuales son de _riesgo moderado_, i.e. no existe una prevalencia de riesgos indidividuales grandes. Desde un punto de vista probabilisticos, se sigue cuando el segundo momento del reclamo individual no se aplica cuando el monto del reclamo tenga colas pesada (i.e. exhiba valores extremos).

---

### Aproximacion analitica modificada por sesgo

Previniendo que el monto agregado de siniestros, $S_t$, pueda exhibir sesgos en su distribucion, debido principalmente a que tiene soporte en la recta real positiva, pero tambien a sesgos en:

* la distribucion de los reclamos individuales

* distribucion del numero de reclamos a traves de $\theta$,

se ha desarrollado una approximacion analitica alternativa a la normal. Esta aproximacion descansa en la distribucion **gamma trasladada** con tres parametros, dada por

\begin{eqnarray}
F_{S_t}(s) 
  & \approx &
  Ga\left(s-s_{t0}|\alpha_{t},\beta_{t}\right),
\end{eqnarray}
donde 

* $s_{j0}$ es un parametro de traslacion,

* $\alpha_t$ es un parametro de forma,

* $\beta_t$ es un parametro de escala.

---

El kernel de la distribucion gamma en cuestion es de la forma
$$
Ga\left(x|\alpha,\beta\right)
  \propto
  x^{\alpha-1} \exp\{-\beta x\}\mathbb{I}_{[0,\infty)}(x).
$$

---

### Calibracion por el metodo de momentos

En la practica, los parametros $\alpha$, $\beta$ y $s_{0}$ se _obtienen/calibran_ a traves del **metodo de momentos (MM)**, 

> El MM consiste en elegir los `parametros de la distribucion` de tal forma que los `tres primeros momentos teoricos` (en este caso) de la distribucion son iguales iguales a los `tres primeros momentos muestrales` de los datos, i.e.

\begin{eqnarray}
\mathbb{E}(S_t)
  & = &
  s_{t0} + \alpha_{t}/\beta_{t}
  \nonumber \\
var(S_{t})
  & = &
  \alpha_{t}/\beta_{t}^{2}
  \nonumber \\
sesgo(S_{t})
  & = &
  2/\alpha_{t}^{1/2}.
  \nonumber
\end{eqnarray}

---

Resolviendo las tres ecuaiones anteriores para los tres parametros en cuestion se obtiene, 
\begin{eqnarray}
\alpha_{t}
  & = &
  4/sesgo(S_t)^{2}
  \nonumber \\
\beta_{t}
  & = &
  2/sesgo(S_{t})sd(S_{t})
  \nonumber \\
s_{t0}
  & = &
  \mathbb{E}(S_{t}) -2sd(S_{t})/sesgo(S_{t}).
  \nonumber
\end{eqnarray}

---

**Supuesto**

Esta aproximacion es valida solo en el caso en que $sesgo(S_t)>0$. En el caso limite cuando $sesgo(S_t)$ decrezca a $0$ se tiene que la aproximacion gamma trasladada converge a la aproximacion normal inducida por el Teorema Central de Limite. **Este es un ejercicio de TAREA a entregarse.**

---

### Aproximacion analitica con variante adicional por sesgo

Consideramos una aproximacion adicional a $F_S(s)$ basada en el ajuste a los primeros tres momentos de su distribucion, como la aproximacion anterior. La nueva aproximacion hace referencia a la distribucion `normal potencia`. 

**Supuesto**

Al igual que el caso anterior, partimos del supuesto $\mathbb{E}(S_t)$, $var(S_t)$ y $sesgo(S_t)$ son conocidos (con $sesgo(S_t)>0$). Se tiene que para todo $s\geq 1$ en el soporte $\mathcal{S}$ de $S$,
\begin{eqnarray}
\mathbb{P}\left( \frac{S_t-\mathbb{E}(S_t)}{sd(S_t)} \leq s+\frac{sesgo(S_t)}{6}(s^2-1)\right)
  & \approx &
  N(s|0,1).
  \nonumber
\end{eqnarray}

---

Es decir,
\begin{eqnarray}
\mathbb{P}\left( \frac{S_t-\mathbb{E}(S_t)}{sd(S_t)} \leq x \right)
  & \approx &
  N\left( \left( \frac{9}{sesgo(S_t)^2} + \frac{6x}{sesgo(S_t)} + 1\right)^{1/2} 
  - \frac{3}{sesgo(S)}|0,1\right),
  \nonumber
\end{eqnarray}
para $s \geq 1$. 

* En casos donde $s < 1$, la aproximacion inducida por el teorema Central de Limite debera ser utilizada.

---

**Implementacion practica**

* **En la practica**, cuando se desee aproximar $F_S(s)$ empleando aproximaciones analiticas, debemos reemplazar $\mathbb{E}(S_t)$, $var(S_t)$ y $sesgo(S_t)$ por sus correspondientes estimadores muestrales.

---

## E) Aproximacion por recursion

La recursion que consideraremos ahora descansa en el caso donde $F_X(x)$, la distribucion del monto individual de reclamo, es discretizada considerando $I$ clases/rangos de reclamos, i.e.
\begin{eqnarray}
  F_X \approx \sum_{i=1}^{I} q_i \delta_{\{x^{*}_i\}},
\end{eqnarray}
donde $\{x^{*}_i\}_{i=1}^{I}$ representan los montos ranqueados de reclamos individuales, y $\{q_i\}_{i=1}^{I}$ las probabilidades de clases correspondientes.

---

**Supuesto**

Es deseble suponer que las clases o los rangos de los montos de reclamos individuales son *equidistantes*.

Así, la distribucion del total de polizas en el portafolio puede agruparse entonces en una `tabla de contingencia`
$$
(N_{ti})_{i=1}^{I},
$$
donde $$N_{ti}$$ denota el numero de polizas que tuvieron el monto de reclamo $x^{*}_{i}$, con la restriccion $$J_t=\sum_{i=1}^{I}N_{ti}.$$ 

---

La tabla de contingencia viene acompaniada con las probabilidades de realizacion de los reclamos individuales, $$\boldsymbol{\theta}=(\theta_1,\ldots,\theta_I),$$ los cuales estan sujetos a 

* $\theta_{i}\geq 0$ para todo $i=a,\ldots,I$

* $\sum_{i=1}^{I}\theta_i=1.$

De esta forma, el monto agregado de siniestros estaria expresado como,
$$
S_t=\sum_{i=1}^{I} N_{tij} x^{*}_{i},
$$
considerando que $\sum_{i=1}^{I}q_i=1$, con $x^{*}_{1}=0$ y $x^{*}_{i}>0$ para todo $i\geq 2$.

---

### Recursion de De Pril

La recursion de De Pril hace referencia a un portafolio de seguros en el que 

* los montos de siniestros individuales estan ranqueados en una escala equidistnate, considerando un nivel base $M$, i.e. $x^{*}_{i}=M\times i$, para $i=1,\ldots, I$, siento $MI$ el monto maximo de cobsertura.

* adicionalmente, cada poliza esta expuesta $D$ riesgos distintos, con correspondientes porbabulidades de siniestos $\theta_1,\theta_2,\ldots,\theta_D$. (El modelo oroginal considera una sola clasificacion / exposicion a riesgos).

---

De esta forma, se define una nueva tabla de contingencia $$(N_{id})_{i=1,d=1}^{I,D},$$ en la que $N_{id}$ denota el numero polizas con el beneficio $i$ y la probabuilidad de reclamo $\theta_j$.

La formula para calcular la distribucion del monto agregado $S_t$ se obtiene como
$$
\mathbb{P}\left(S_t=y\right)=\frac{1}{y}\sum_{i=1}
^{min\{y,M\}}\sum_{d=1}^{y/d}p(y-id)h(i,d),$$
con $$p(0)=\prod_{i=1}^{I}\prod_{d=1}^{D}(1-\theta_d)^{n_{id}},$$
y
$$h(i,k)=i(-1)^{k-1}\sum_{d=1}^{D}n_{id}\left(\frac{\theta_d}{1-\theta_d}\right)^{k}.$$

---

**Recursion**

La formula anterior tiene una forma simple de calcularse a traves de la siguiente recursion,
$$
p_{K}(0)=p(0),
$$ y
$$
p_{K}(y)=\frac{1}{y}\sum_{i=1}^{min\{y,M\}} \sum_{k=1}^{min\{K,y/i\}}p_{K}(y-ik)h(i,k),
$$
considerando a $K$ como un parametro adicional. Usualente $K:=4$ es una consideracion viable, pero recordemos que $K$ puede ser cualqueir entero poitivo.

---

# Temas siguientes

* Metodo de momentos para aproximar $F_{S}(s)$

* Recursiones en le modelo de riesgo colectivo (Recursion de De Pril y Panjer)